/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#4ae176',
        'secondary-container': '#00b954',
        'inverse-surface': '#d5e3fd',
        'on-error': '#690005',
        'surface-container': '#122033',
        'outline': '#8c909f',
        'on-secondary-container': '#004119',
        'error-container': '#93000a',
        'primary-container': '#4d8eff',
        'tertiary-container': '#ca8100',
        'on-primary-fixed-variant': '#004395',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary': '#472a00',
        'secondary-fixed': '#6bff8f',
        'tertiary-fixed': '#ffddb8',
        'surface-container-highest': '#273649',
        'surface-container-lowest': '#010f21',
        'on-tertiary-fixed': '#2a1700',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary': '#002e6a',
        'surface-dim': '#051426',
        'on-secondary-fixed-variant': '#005321',
        'surface': '#051426',
        'error': '#ffb4ab',
        'primary': '#adc6ff',
        'surface-tint': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'primary-fixed-dim': '#adc6ff',
        'inverse-on-surface': '#233144',
        'inverse-primary': '#005ac2',
        'on-primary-container': '#00285d',
        'surface-container-high': '#1c2b3e',
        'on-surface-variant': '#c2c6d6',
        'surface-container-low': '#0d1c2f',
        'on-error-container': '#ffdad6',
        'secondary': '#4ae176',
        'surface-variant': '#273649',
        'on-secondary-fixed': '#002109',
        'surface-bright': '#2c3a4e',
        'on-secondary': '#003915',
        'on-surface': '#d5e3fd',
        'outline-variant': '#424754',
        'primary-fixed': '#d8e2ff',
        'on-tertiary-container': '#3e2400',
        'on-background': '#d5e3fd',
        'tertiary': '#ffb95f',
        'background': '#051426',
      },
      fontFamily: {
        'mono': ['"JetBrains Mono"', 'monospace'],
        'sans': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
